sudo: required
services: 
  - docker

before_install:
  - docker build -t adeel/react-test -f ./client/Dockerfile.dev ./client


script: 
  - docker run -e CI=true adeel/react-test npm test


after_success:
  - docker build -t adeel/multi-client ./client
  - docker build -t adeel/multi-nginx  ./nginx 
  - docker build -t adeel/multi-server ./server
  - docker build -t adeel/multi-worker ./worker

  # Login to the docker CLI, the credentials are given in the TRAVIS account as env variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the images and push to dockerhub
  - docker push adeel/multi-client
  - docker push adeel/multi-nginx
  - docker push adeel/multi-server
  - docker push adeel/multi-worker



